// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhZ3ZiZzCIezFFJCoROW9wHNOn7X02AtE',
    appId: '1:322306948280:web:c3f3896fe32ea2b522484d',
    messagingSenderId: '322306948280',
    projectId: 'insta-clone-17',
    authDomain: 'insta-clone-17.firebaseapp.com',
    storageBucket: 'insta-clone-17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaAhO1cUeyUjxbFxx8C3jkYr1ZKzcuULI',
    appId: '1:322306948280:android:d736033391604dab22484d',
    messagingSenderId: '322306948280',
    projectId: 'insta-clone-17',
    storageBucket: 'insta-clone-17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_ZiPg447UT65SIO5knX4BI9HX1tqZXo',
    appId: '1:322306948280:ios:9365ed8041470b6322484d',
    messagingSenderId: '322306948280',
    projectId: 'insta-clone-17',
    storageBucket: 'insta-clone-17.appspot.com',
    iosClientId: '322306948280-1t85r2eg4nmhen2iel5ob27kbnvhnfnf.apps.googleusercontent.com',
    iosBundleId: 'com.kurbatxx.instaclone.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz_ZiPg447UT65SIO5knX4BI9HX1tqZXo',
    appId: '1:322306948280:ios:9365ed8041470b6322484d',
    messagingSenderId: '322306948280',
    projectId: 'insta-clone-17',
    storageBucket: 'insta-clone-17.appspot.com',
    iosClientId: '322306948280-1t85r2eg4nmhen2iel5ob27kbnvhnfnf.apps.googleusercontent.com',
    iosBundleId: 'com.kurbatxx.instaclone.instaClone',
  );
}
